# Generated by Django 5.0.2 on 2024-03-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEntity',
            fields=[
                ('house_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('primary_owner', models.CharField(max_length=255)),
                ('num_people', models.IntegerField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
