# Generated by Django 5.0.2 on 2024-02-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentity',
            name='house_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communityentity',
            name='primary_owner',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
