# Generated by Django 5.0.2 on 2024-02-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_ticket_coordinator_alter_task_assigned_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New/Open', 'New/Open'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('On Hold', 'On Hold'), ('Resolved/Closed', 'Resolved/Closed'), ('Cancelled', 'Cancelled'), ('Reopened', 'Reopened')], max_length=20),
        ),
    ]
