# Generated by Django 5.0.2 on 2024-03-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_history_end_time_history_start_time_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
