# Generated by Django 5.0.2 on 2024-02-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='worker',
        ),
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Received', 'Recieved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('New/Open', 'New/Open'), ('In Progress', 'In Progress'), ('Pending Approval', 'Pending Approval'), ('Pending Parts', 'Pending Parts'), ('Resolved/Closed', 'Resolved/Closed'), ('Cancelled', 'Cancelled'), ('Reopened', 'Reopened')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('New/Open', 'New/Open'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('On Hold', 'On Hold'), ('Resolved/Closed', 'Resolved/Closed'), ('Cancelled', 'Cancelled'), ('Reopened', 'Reopened')], max_length=20, null=True),
        ),
    ]
