# Generated by Django 5.0.2 on 2024-02-18 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0006_task_date_opened_alter_quote_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
