# Generated by Django 5.0.2 on 2024-02-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_house_alter_ticket_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.ticket'),
        ),
    ]
