# Generated by Django 5.0.2 on 2024-02-18 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_task_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.house'),
        ),
    ]
