# Generated by Django 5.0.2 on 2024-02-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_ticket_workorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='short_description',
            new_name='subject',
        ),
    ]
