# Generated by Django 5.0.2 on 2024-02-19 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_units', '0001_initial'),
        ('tracker', '0012_rename_short_description_workorder_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_units.communityentity'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='task',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
