# Generated by Django 5.0.2 on 2024-02-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_workorder_house_remove_quote_task_delete_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_group',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='image',
        ),
    ]
