# Generated by Django 5.0.2 on 2024-02-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_workorder_assigned_group_workorder_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_group',
        ),
    ]
