# Generated by Django 5.0.2 on 2024-02-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_remove_workorder_assigned_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='image',
        ),
    ]
