# Generated by Django 5.0.2 on 2024-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_task_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='diagnostics',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
