# Generated by Django 5.0.2 on 2024-02-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_alter_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='ticket',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ticket',
            new_name='work_order',
        ),
    ]
