# Generated by Django 5.0.2 on 2024-02-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_quote_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='amount',
            new_name='amountCAD',
        ),
    ]
